gitlab-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      pass: "{{ env_var('POSTGRES_PASS') }}"
      dbname: "{{ env_var('POSTGRES_DBNAME') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
