rt_dev_local:
  target: duckdb
  outputs:
    duckdb:
      threads: 4
      title: "Real-time demo (local)"
      type: duckdb
      path: "local_databases/rt_dev_local.db"
      schema: "real_time"
      extensions:
        - httpfs
        - parquet
      settings:
        # Local Minio
        s3_region: us-east-1
        s3_endpoint: 'localhost:19000'
        s3_access_key_id: "minio_abcde_k1234567"
        s3_secret_access_key: "minio_abcde_k1234567_secret1234567890123"
        s3_use_ssl: false
        s3_url_style: 'path'

rt_dev:
  target: motherduck
  outputs:
    motherduck:
      threads: 4
      title: "Real-time demo (MotherDuck)"
      type: duckdb
      path: "md:my_db"
      schema: "real_time"
      extensions:
        - httpfs
        - parquet
      settings:
        # Standard AWS S3
        s3_region: us-east-1
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
    redshift:
      threads: 2
      title: "Real-time demo (Redshift)"
      type: redshift
      # host: "stg11-tiger-dev-redshift.cpo104ej0t9v.us-east-1.redshift.amazonaws.com"
      host: "jacek-test-serverless.972873489489.us-east-1.redshift-serverless.amazonaws.com"
      port: 5439
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      dbname: "dev"
      schema: "cicd_input_stage"
