default:
  target: github2postgres
  # TODO - use dbt vault for credentials shared by dbt and GoodData once GoodData supports vault for data source credentials
  # https://dbtvault.readthedocs.io/en/latest/
  outputs:
    github2postgres:
      title: "{{ env_var('DBT_TARGET_TITLE') }}"
      type: postgres
      threads: 1
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASS') }}"
      dbname: "{{ env_var('POSTGRES_DBNAME') }}"
      schema: "{{ env_var('POSTGRES_INPUT_SCHEMA') }}"
