name: Extract, Load, Transform, and Analytics (Staging Schedule)

on:
  schedule:
    - cron: "00 4 * * *"

jobs:
  elta:
    name: ELTA (staging)
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "staging"
      BRANCH_NAME: "main"
      DEPLOY_ANALYTICS: "false"
    secrets: inherit
