name: Extract, Load, Transform, and Analytics (Prod Schedule)

on:
  schedule:
    - cron: "00 5 * * *"

jobs:
  elta:
    name: ELTA (prod)
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "prod"
      BRANCH_NAME: "prod"
      DEPLOY_ANALYTICS: "false"
    secrets: inherit

  elta-cloud:
    name: ELTA (prod cloud)
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "prod_cloud"
      BRANCH_NAME: "prod"
      DEPLOY_ANALYTICS: "false"
      DBT_CLOUD: "true"
    secrets: inherit

  # Branch for MotherDuck DB.
  # GoodData now supports MotherDuck only in Labs environment
  #   because the issue with extensions downloaded in runtime.
  elta-labs-motherduck:
    name: ELTA (prod MotherDuck)
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "prod_labs_motherduck"
      BRANCH_NAME: "prod"
      DEPLOY_ANALYTICS: "false"
    secrets: inherit
