name: Extract, Load, Transform, and Analytics (Staging Schedule)

on:
  schedule:
    - cron: "00 4 * * *"

jobs:
  elta:
    name: ELTA (staging)
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "staging"
      BRANCH_NAME: "main"
      DEPLOY_ANALYTICS: "false"
    secrets: inherit

  elta-cloud:
    name: ELTA (staging cloud)
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "staging_cloud"
      BRANCH_NAME: "main"
      DEPLOY_ANALYTICS: "false"
      DBT_CLOUD: "true"
    secrets: inherit

  # Branch for MotherDuck DB.
  # GoodData now supports MotherDuck only in Labs environment
  #   because the issue with extensions downloaded in runtime.
  elta-labs-motherduck:
    name: ELTA (staging MotherDuck)
    uses: ./.github/workflows/reusable_elta.yml
    with:
      ENVIRONMENT: "staging_labs_motherduck"
      BRANCH_NAME: "main"
      DEPLOY_ANALYTICS: "false"
    secrets: inherit
